### ISSUE TITLE
conditionally fail action

### ISSUE THREAD

**Issue by jetersen** [xt0rted/pull-request-comment-branch#116]
would be nice to avoid failing the action.

I have workflow that deploys artifacts on pull request comment and on master branch pushes.

```yaml
on:
  push:
    branches:
      - 'master'
  issue_comment:
    types:
      - created
```
