### ISSUE TITLE
Error: Cannot read property 'name' of null

### ISSUE THREAD

**Issue by flcdrg** [xt0rted/pull-request-comment-branch#213]
Seeing this failure when I close a pull request

```text
Run xt0rted/pull-request-comment-branch@v1
  with:
    repo_token: ***
Error: Cannot read property 'name' of null
(node:1544) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'name' of null
    at pullRequestDetails (/home/runner/work/_actions/xt0rted/pull-request-comment-branch/v1/webpack:/pull-request-comment-branch/src/PullRequests.ts:38:1)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at run (/home/runner/work/_actions/xt0rted/pull-request-comment-branch/v1/webpack:/pull-request-comment-branch/src/main.ts:9:1)
(node:1544) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1544) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Workflow looks similar to this:

```yaml
name: Slash Command Dispatch
on:
  issue_comment:
    types: [created]
jobs:
  slashCommandDispatch:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - name: Slash Command Repository Dispatch
        uses: peter-evans/slash-command-dispatch@v2
        with:
          token: ${{ secrets.MYTOKEN }}
          commands: |
            rebase
          permission: write
          issue-type: pull-request

      - uses: xt0rted/pull-request-comment-branch@v1
        id: comment-branch

      - name: Slash Command Workflow Dispatch
        uses: peter-evans/slash-command-dispatch@v2
        with:
          token: ${{ secrets.MYTOKEN }}
          commands: |
            lockfiles
          permission: write
          issue-type: pull-request
          dispatch-type: workflow
          static-args: ref=${{ steps.comment-branch.outputs.head_ref }}  
```
